env:
  webextensions: true
  browser: true
  es2022: true
extends:
  - standard
  - eslint:all
  - standard-with-typescript
  - plugin:@typescript-eslint/all
  - plugin:prettier/recommended
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  project: ./tsconfig.json
ignorePatterns: vite-env.d.ts
rules:
  capitalized-comments: off
  default-case: off
  func-style:
    - error
    - declaration
  max-lines-per-function: off
  max-statements: off
  multiline-comment-style:
    - error
    - separate-lines
  no-console: off
  no-ternary: off
  no-continue: off
  no-alert: off
  '@typescript-eslint/no-magic-numbers':
    - error
    - ignore:
        - 0
        - 1
  '@typescript-eslint/no-type-alias': off
  '@typescript-eslint/prefer-readonly-parameter-types': off
  '@typescript-eslint/prefer-enum-initializers': off
